spring.application.name=docker
spring.datasource.username=bender
spring.datasource.url=jdbc:postgresql://localhost:5433/bender_spring
spring.datasource.password=bender

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.error.include-message=always